language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-head
before_install: gem install bundler -v 1.10.6
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
install:
  - bundle install --retry=3
script:
  - bundle exec rake ci
